---
- hosts: all
  become: true
  vars_files:
    - vars/vars.yml

  tasks:
    - name: Install software packages
      command: apt install software-properties-common

    - name: Add repository ppa:ondrej/php
      apt_repository:
        repo="ppa:ondrej/php" state=present

    - name: Update repo
      apt: update_cache=yes

    - name: Install php7.4
      apt: 
        name: php7.4 
        state: present


    - name: copy my "index.php page to the host server[remote]
      copy:
        src: /home/vagrant/ansible_tf/index.php
        dest: /var/www/html/index.php

